version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  fail_on_warning: false # set to false due to flaky sphinx cross-linking when using sphinx-autoapi
  
python:
  install:
    - requirements: user_doc/sphinx_requirements.txt

