# autogenerated for OGA Tool on 2021-11-15 10:05:47.574628

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_progressdlg',
           'ui_rungriddlg',
           'ui_runpedlg']
