# autogenerated for OGA Tool on 2022-07-22 12:09:33.318899

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_progressdlg',
           'ui_unifiedwindow']
