# autogenerated for OGA Tool on 2021-09-20 14:00:50.229601

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_progressdlg',
           'ui_rungriddlg',
           'ui_runpedlg']
