# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunGridDlg.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateGridDlg(object):
    def setupUi(self, CreateGridDlg):
        CreateGridDlg.setObjectName("CreateGridDlg")
        CreateGridDlg.resize(309, 391)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateGridDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(CreateGridDlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sdInputLbl = ElideLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdInputLbl.sizePolicy().hasHeightForWidth())
        self.sdInputLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.sdInputLbl.setFont(font)
        self.sdInputLbl.setObjectName("sdInputLbl")
        self.gridLayout.addWidget(self.sdInputLbl, 0, 1, 1, 1)
        self.sdInputButton = QtWidgets.QPushButton(self.groupBox)
        self.sdInputButton.setObjectName("sdInputButton")
        self.gridLayout.addWidget(self.sdInputButton, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.ldInputLbl = ElideLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldInputLbl.sizePolicy().hasHeightForWidth())
        self.ldInputLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.ldInputLbl.setFont(font)
        self.ldInputLbl.setObjectName("ldInputLbl")
        self.gridLayout.addWidget(self.ldInputLbl, 1, 1, 1, 1)
        self.ldInputButton = QtWidgets.QPushButton(self.groupBox)
        self.ldInputButton.setObjectName("ldInputButton")
        self.gridLayout.addWidget(self.ldInputButton, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.widthField = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthField.sizePolicy().hasHeightForWidth())
        self.widthField.setSizePolicy(sizePolicy)
        self.widthField.setMaximumSize(QtCore.QSize(54, 16777215))
        self.widthField.setObjectName("widthField")
        self.gridLayout.addWidget(self.widthField, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.heightField = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightField.sizePolicy().hasHeightForWidth())
        self.heightField.setSizePolicy(sizePolicy)
        self.heightField.setMaximumSize(QtCore.QSize(54, 16777215))
        self.heightField.setObjectName("heightField")
        self.gridLayout.addWidget(self.heightField, 3, 1, 1, 1)
        self.projectionCB = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectionCB.sizePolicy().hasHeightForWidth())
        self.projectionCB.setSizePolicy(sizePolicy)
        self.projectionCB.setObjectName("projectionCB")
        self.gridLayout.addWidget(self.projectionCB, 4, 0, 1, 1)
        self.projectionLbl = ElideLabel(self.groupBox)
        self.projectionLbl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectionLbl.sizePolicy().hasHeightForWidth())
        self.projectionLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.projectionLbl.setFont(font)
        self.projectionLbl.setObjectName("projectionLbl")
        self.gridLayout.addWidget(self.projectionLbl, 4, 1, 1, 1)
        self.projectionButton = QtWidgets.QPushButton(self.groupBox)
        self.projectionButton.setEnabled(False)
        self.projectionButton.setObjectName("projectionButton")
        self.gridLayout.addWidget(self.projectionButton, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(CreateGridDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.finalGridLbl = ElideLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finalGridLbl.sizePolicy().hasHeightForWidth())
        self.finalGridLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.finalGridLbl.setFont(font)
        self.finalGridLbl.setObjectName("finalGridLbl")
        self.gridLayout_2.addWidget(self.finalGridLbl, 0, 1, 1, 1)
        self.finalGridButton = QtWidgets.QPushButton(self.groupBox_2)
        self.finalGridButton.setObjectName("finalGridButton")
        self.gridLayout_2.addWidget(self.finalGridButton, 0, 2, 1, 1)
        self.lgsdldGridCB = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lgsdldGridCB.sizePolicy().hasHeightForWidth())
        self.lgsdldGridCB.setSizePolicy(sizePolicy)
        self.lgsdldGridCB.setObjectName("lgsdldGridCB")
        self.gridLayout_2.addWidget(self.lgsdldGridCB, 1, 0, 1, 1)
        self.lgsdldGridLbl = ElideLabel(self.groupBox_2)
        self.lgsdldGridLbl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lgsdldGridLbl.sizePolicy().hasHeightForWidth())
        self.lgsdldGridLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lgsdldGridLbl.setFont(font)
        self.lgsdldGridLbl.setObjectName("lgsdldGridLbl")
        self.gridLayout_2.addWidget(self.lgsdldGridLbl, 1, 1, 1, 1)
        self.lgsdldGridButton = QtWidgets.QPushButton(self.groupBox_2)
        self.lgsdldGridButton.setEnabled(False)
        self.lgsdldGridButton.setObjectName("lgsdldGridButton")
        self.gridLayout_2.addWidget(self.lgsdldGridButton, 1, 2, 1, 1)
        self.lgsdDatasetCB = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lgsdDatasetCB.sizePolicy().hasHeightForWidth())
        self.lgsdDatasetCB.setSizePolicy(sizePolicy)
        self.lgsdDatasetCB.setObjectName("lgsdDatasetCB")
        self.gridLayout_2.addWidget(self.lgsdDatasetCB, 2, 0, 1, 1)
        self.lgsdDatasetLbl = ElideLabel(self.groupBox_2)
        self.lgsdDatasetLbl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lgsdDatasetLbl.sizePolicy().hasHeightForWidth())
        self.lgsdDatasetLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lgsdDatasetLbl.setFont(font)
        self.lgsdDatasetLbl.setObjectName("lgsdDatasetLbl")
        self.gridLayout_2.addWidget(self.lgsdDatasetLbl, 2, 1, 1, 1)
        self.lgsdDatasetButton = QtWidgets.QPushButton(self.groupBox_2)
        self.lgsdDatasetButton.setEnabled(False)
        self.lgsdDatasetButton.setObjectName("lgsdDatasetButton")
        self.gridLayout_2.addWidget(self.lgsdDatasetButton, 2, 2, 1, 1)
        self.baseGridCB = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseGridCB.sizePolicy().hasHeightForWidth())
        self.baseGridCB.setSizePolicy(sizePolicy)
        self.baseGridCB.setObjectName("baseGridCB")
        self.gridLayout_2.addWidget(self.baseGridCB, 3, 0, 1, 1)
        self.baseGridLbl = ElideLabel(self.groupBox_2)
        self.baseGridLbl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseGridLbl.sizePolicy().hasHeightForWidth())
        self.baseGridLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.baseGridLbl.setFont(font)
        self.baseGridLbl.setObjectName("baseGridLbl")
        self.gridLayout_2.addWidget(self.baseGridLbl, 3, 1, 1, 1)
        self.baseGridButton = QtWidgets.QPushButton(self.groupBox_2)
        self.baseGridButton.setEnabled(False)
        self.baseGridButton.setObjectName("baseGridButton")
        self.gridLayout_2.addWidget(self.baseGridButton, 3, 2, 1, 1)
        self.gridDataframeCB = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridDataframeCB.sizePolicy().hasHeightForWidth())
        self.gridDataframeCB.setSizePolicy(sizePolicy)
        self.gridDataframeCB.setObjectName("gridDataframeCB")
        self.gridLayout_2.addWidget(self.gridDataframeCB, 4, 0, 1, 1)
        self.gridDataframeLbl = ElideLabel(self.groupBox_2)
        self.gridDataframeLbl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridDataframeLbl.sizePolicy().hasHeightForWidth())
        self.gridDataframeLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.gridDataframeLbl.setFont(font)
        self.gridDataframeLbl.setObjectName("gridDataframeLbl")
        self.gridLayout_2.addWidget(self.gridDataframeLbl, 4, 1, 1, 1)
        self.gridDataframeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.gridDataframeButton.setEnabled(False)
        self.gridDataframeButton.setObjectName("gridDataframeButton")
        self.gridLayout_2.addWidget(self.gridDataframeButton, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateGridDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CreateGridDlg)
        self.buttonBox.accepted.connect(CreateGridDlg.accept)
        self.buttonBox.rejected.connect(CreateGridDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateGridDlg)

    def retranslateUi(self, CreateGridDlg):
        _translate = QtCore.QCoreApplication.translate
        CreateGridDlg.setWindowTitle(_translate("CreateGridDlg", "Create PE Grid"))
        self.groupBox.setTitle(_translate("CreateGridDlg", "Inputs"))
        self.label_3.setText(_translate("CreateGridDlg", "SD Input File:"))
        self.sdInputLbl.setText(_translate("CreateGridDlg", "None"))
        self.sdInputButton.setText(_translate("CreateGridDlg", "Select..."))
        self.label_6.setText(_translate("CreateGridDlg", "LD Input File:"))
        self.ldInputLbl.setText(_translate("CreateGridDlg", "None"))
        self.ldInputButton.setText(_translate("CreateGridDlg", "Select..."))
        self.label.setText(_translate("CreateGridDlg", "Grid Width:"))
        self.widthField.setText(_translate("CreateGridDlg", "1000"))
        self.label_2.setText(_translate("CreateGridDlg", "Grid Height:"))
        self.heightField.setText(_translate("CreateGridDlg", "1000"))
        self.projectionCB.setText(_translate("CreateGridDlg", "Projection:"))
        self.projectionLbl.setText(_translate("CreateGridDlg", "None"))
        self.projectionButton.setText(_translate("CreateGridDlg", "Select..."))
        self.groupBox_2.setTitle(_translate("CreateGridDlg", "Outputs"))
        self.label_9.setText(_translate("CreateGridDlg", "PE Grid:"))
        self.finalGridLbl.setText(_translate("CreateGridDlg", "None"))
        self.finalGridButton.setText(_translate("CreateGridDlg", "Select..."))
        self.lgsdldGridCB.setText(_translate("CreateGridDlg", "LG-SD-LD Grid:"))
        self.lgsdldGridLbl.setText(_translate("CreateGridDlg", "None"))
        self.lgsdldGridButton.setText(_translate("CreateGridDlg", "Select..."))
        self.lgsdDatasetCB.setText(_translate("CreateGridDlg", "LG-SD Dataset:"))
        self.lgsdDatasetLbl.setText(_translate("CreateGridDlg", "None"))
        self.lgsdDatasetButton.setText(_translate("CreateGridDlg", "Select..."))
        self.baseGridCB.setText(_translate("CreateGridDlg", "Base Grid:"))
        self.baseGridLbl.setText(_translate("CreateGridDlg", "None"))
        self.baseGridButton.setText(_translate("CreateGridDlg", "Select..."))
        self.gridDataframeCB.setText(_translate("CreateGridDlg", "Grid Dataframe:"))
        self.gridDataframeLbl.setText(_translate("CreateGridDlg", "None"))
        self.gridDataframeButton.setText(_translate("CreateGridDlg", "Select..."))
from ..ElideLabelWidget import ElideLabel
