# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunPEDlg.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 336)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.targetCombo = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetCombo.sizePolicy().hasHeightForWidth())
        self.targetCombo.setSizePolicy(sizePolicy)
        self.targetCombo.setObjectName("targetCombo")
        self.targetCombo.addItem("")
        self.targetCombo.addItem("")
        self.gridLayout.addWidget(self.targetCombo, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gdbLbl = ElideLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdbLbl.sizePolicy().hasHeightForWidth())
        self.gdbLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.gdbLbl.setFont(font)
        self.gdbLbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gdbLbl.setObjectName("gdbLbl")
        self.gridLayout.addWidget(self.gdbLbl, 0, 1, 1, 1)
        self.gridFileLbl = ElideLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFileLbl.sizePolicy().hasHeightForWidth())
        self.gridFileLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.gridFileLbl.setFont(font)
        self.gridFileLbl.setObjectName("gridFileLbl")
        self.gridLayout.addWidget(self.gridFileLbl, 1, 1, 1, 1)
        self.gridFileButton = QtWidgets.QPushButton(self.groupBox)
        self.gridFileButton.setObjectName("gridFileButton")
        self.gridLayout.addWidget(self.gridFileButton, 1, 3, 1, 1)
        self.gdbButton = QtWidgets.QPushButton(self.groupBox)
        self.gdbButton.setObjectName("gdbButton")
        self.gridLayout.addWidget(self.gdbButton, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.s1GridOutCB = QtWidgets.QCheckBox(self.groupBox_2)
        self.s1GridOutCB.setObjectName("s1GridOutCB")
        self.gridLayout_2.addWidget(self.s1GridOutCB, 1, 0, 1, 1)
        self.finalGridLbl = ElideLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.finalGridLbl.setFont(font)
        self.finalGridLbl.setScaledContents(False)
        self.finalGridLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.finalGridLbl.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.finalGridLbl.setObjectName("finalGridLbl")
        self.gridLayout_2.addWidget(self.finalGridLbl, 0, 1, 1, 1)
        self.finalGridButton = QtWidgets.QPushButton(self.groupBox_2)
        self.finalGridButton.setObjectName("finalGridButton")
        self.gridLayout_2.addWidget(self.finalGridButton, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.s1StatOutLbl = ElideLabel(self.groupBox_2)
        self.s1StatOutLbl.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.s1StatOutLbl.setFont(font)
        self.s1StatOutLbl.setObjectName("s1StatOutLbl")
        self.gridLayout_2.addWidget(self.s1StatOutLbl, 2, 1, 1, 1)
        self.s1StatOutButton = QtWidgets.QPushButton(self.groupBox_2)
        self.s1StatOutButton.setEnabled(False)
        self.s1StatOutButton.setObjectName("s1StatOutButton")
        self.gridLayout_2.addWidget(self.s1StatOutButton, 2, 2, 1, 1)
        self.PEDataframeOutCB = QtWidgets.QCheckBox(self.groupBox_2)
        self.PEDataframeOutCB.setObjectName("PEDataframeOutCB")
        self.gridLayout_2.addWidget(self.PEDataframeOutCB, 4, 0, 1, 1)
        self.s1StatOutCB = QtWidgets.QCheckBox(self.groupBox_2)
        self.s1StatOutCB.setObjectName("s1StatOutCB")
        self.gridLayout_2.addWidget(self.s1StatOutCB, 2, 0, 1, 1)
        self.PEDataframeOutButton = QtWidgets.QPushButton(self.groupBox_2)
        self.PEDataframeOutButton.setEnabled(False)
        self.PEDataframeOutButton.setObjectName("PEDataframeOutButton")
        self.gridLayout_2.addWidget(self.PEDataframeOutButton, 4, 2, 1, 1)
        self.s1GridOutButton = QtWidgets.QPushButton(self.groupBox_2)
        self.s1GridOutButton.setEnabled(False)
        self.s1GridOutButton.setObjectName("s1GridOutButton")
        self.gridLayout_2.addWidget(self.s1GridOutButton, 1, 2, 1, 1)
        self.s1GridOutLbl = ElideLabel(self.groupBox_2)
        self.s1GridOutLbl.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.s1GridOutLbl.setFont(font)
        self.s1GridOutLbl.setObjectName("s1GridOutLbl")
        self.gridLayout_2.addWidget(self.s1GridOutLbl, 1, 1, 1, 1)
        self.s3DataframeOutCB = QtWidgets.QCheckBox(self.groupBox_2)
        self.s3DataframeOutCB.setObjectName("s3DataframeOutCB")
        self.gridLayout_2.addWidget(self.s3DataframeOutCB, 3, 0, 1, 1)
        self.s3DataframeOutLbl = ElideLabel(self.groupBox_2)
        self.s3DataframeOutLbl.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.s3DataframeOutLbl.setFont(font)
        self.s3DataframeOutLbl.setObjectName("s3DataframeOutLbl")
        self.gridLayout_2.addWidget(self.s3DataframeOutLbl, 3, 1, 1, 1)
        self.s3DataframeOutButton = QtWidgets.QPushButton(self.groupBox_2)
        self.s3DataframeOutButton.setEnabled(False)
        self.s3DataframeOutButton.setObjectName("s3DataframeOutButton")
        self.gridLayout_2.addWidget(self.s3DataframeOutButton, 3, 2, 1, 1)
        self.PEDataframeOutLbl = ElideLabel(self.groupBox_2)
        self.PEDataframeOutLbl.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.PEDataframeOutLbl.setFont(font)
        self.PEDataframeOutLbl.setObjectName("PEDataframeOutLbl")
        self.gridLayout_2.addWidget(self.PEDataframeOutLbl, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculate PE Score"))
        self.groupBox.setTitle(_translate("Dialog", "Inputs"))
        self.targetCombo.setItemText(0, _translate("Dialog", "DA"))
        self.targetCombo.setItemText(1, _translate("Dialog", "DS"))
        self.label_4.setText(_translate("Dialog", "Target Class:"))
        self.label.setText(_translate("Dialog", "Source .gdb File:"))
        self.label_2.setText(_translate("Dialog", "PE Grid File:"))
        self.gdbLbl.setText(_translate("Dialog", "None"))
        self.gridFileLbl.setText(_translate("Dialog", "None"))
        self.gridFileButton.setText(_translate("Dialog", "Select..."))
        self.gdbButton.setText(_translate("Dialog", "Select..."))
        self.groupBox_2.setTitle(_translate("Dialog", "Outputs"))
        self.s1GridOutCB.setText(_translate("Dialog", "Step 1 Grid:"))
        self.finalGridLbl.setText(_translate("Dialog", "None"))
        self.finalGridButton.setText(_translate("Dialog", "Select..."))
        self.label_3.setText(_translate("Dialog", "PE Grid Score File:"))
        self.s1StatOutLbl.setText(_translate("Dialog", "None"))
        self.s1StatOutButton.setText(_translate("Dialog", "Select..."))
        self.PEDataframeOutCB.setText(_translate("Dialog", "PE Dataframe:"))
        self.s1StatOutCB.setText(_translate("Dialog", "Step 1  Stats:"))
        self.PEDataframeOutButton.setText(_translate("Dialog", "Select..."))
        self.s1GridOutButton.setText(_translate("Dialog", "Select..."))
        self.s1GridOutLbl.setText(_translate("Dialog", "None"))
        self.s3DataframeOutCB.setText(_translate("Dialog", "Step 3 Dataframe:"))
        self.s3DataframeOutLbl.setText(_translate("Dialog", "None"))
        self.s3DataframeOutButton.setText(_translate("Dialog", "Select..."))
        self.PEDataframeOutLbl.setText(_translate("Dialog", "None"))
from ..ElideLabelWidget import ElideLabel
