# autogenerated for OGA Tool on 2023-01-30 15:16:46.230532

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_aboutdlg',
           'ui_progressdlg',
           'ui_resultsdlg',
           'ui_unifiedwindow']
