# autogenerated for OGA Tool on 2022-08-05 10:11:30.574091

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_progressdlg',
           'ui_resultsdlg',
           'ui_unifiedwindow']
