# autogenerated for OGA Tool on 2023-01-17 09:50:09.659170

"""Auto-generated files created by the QT tools suite. Do not edit directly."""

__all__ = ['ui_progressdlg',
           'ui_resultsdlg',
           'ui_unifiedwindow']
