# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultsDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resultDialog(object):
    def setupUi(self, resultDialog):
        resultDialog.setObjectName("resultDialog")
        resultDialog.resize(1077, 745)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(resultDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(resultDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.previewTab = QtWidgets.QWidget()
        self.previewTab.setObjectName("previewTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.previewTab)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultTreeView = QtWidgets.QTreeView(self.previewTab)
        self.resultTreeView.setObjectName("resultTreeView")
        self.resultTreeView.header().setVisible(False)
        self.horizontalLayout_3.addWidget(self.resultTreeView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.coordLbl = QtWidgets.QLabel(self.previewTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.coordLbl.setFont(font)
        self.coordLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordLbl.setObjectName("coordLbl")
        self.verticalLayout.addWidget(self.coordLbl)
        self.frame = QtWidgets.QFrame(self.previewTab)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rasterView = GaiaQtGLWidget(self.frame)
        self.rasterView.setMouseTracking(True)
        self.rasterView.setObjectName("rasterView")
        self.verticalLayout_3.addWidget(self.rasterView)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.previewTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gradientValButton = GradientButton(self.previewTab)
        self.gradientValButton.setEnabled(False)
        self.gradientValButton.setText("")
        self.gradientValButton.setObjectName("gradientValButton")
        self.horizontalLayout.addWidget(self.gradientValButton)
        self.label = QtWidgets.QLabel(self.previewTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.previewTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logTab)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logTextView = QtWidgets.QPlainTextEdit(self.logTab)
        self.logTextView.setUndoRedoEnabled(False)
        self.logTextView.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.logTextView.setReadOnly(True)
        self.logTextView.setObjectName("logTextView")
        self.verticalLayout_2.addWidget(self.logTextView)
        self.tabWidget.addTab(self.logTab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(resultDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(resultDialog)

    def retranslateUi(self, resultDialog):
        _translate = QtCore.QCoreApplication.translate
        resultDialog.setWindowTitle(_translate("resultDialog", "Results Preview"))
        self.coordLbl.setText(_translate("resultDialog", "--"))
        self.label_2.setText(_translate("resultDialog", "0.0"))
        self.label.setText(_translate("resultDialog", "1.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.previewTab), _translate("resultDialog", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("resultDialog", "Run Log"))
from ..visualizer.qt_support.colorbuttons_qt import GradientButton
from ..visualizer.qt_support.qt_GaiaGLWidget import GaiaQtGLWidget
